In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset

In [6]:
df = pd.read_csv('/content/archive (2).zip',header = None,names = ['category','authors','date','clean_headline','clean_description','year','month','headline_char_count','headline_word_count','avg_word_length'])

/tmp/ipykernel_18242/3048134261.py:1: DtypeWarning: Columns (5,6,7,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/archive (2).zip',header = None,names = ['category','authors','date','clean_headline','clean_description','year','month','headline_char_count','headline_word_count','avg_word_length'])

In [7]:
df.shape

(206642, 10)

In [8]:
df.head()

,category,authors,date,clean_headline,clean_description,year,month,headline_char_count,headline_word_count,avg_word_length
0,category,authors,date,clean_headline,clean_description,year,month,headline_char_count,headline_word_count,avg_word_length
1,U.S. NEWS,"Carla K. Johnson, AP",2022-09-23,over million americans roll up sleeves for omi...,health experts said it is too early to predict...,2022,9,73,10,7.3
2,U.S. NEWS,Mary Papenfuss,2022-09-23,american airlines flyer charged banned for lif...,he was subdued by passengers and crew when he ...,2022,9,88,13,6.769230769230769
3,COMEDY,Elyse Wanshel,2022-09-23,of the funniest tweets about cats and dogs thi...,until you have a dog you dont understand what ...,2022,9,57,11,5.181818181818182
4,PARENTING,Caroline Bologna,2022-09-23,the funniest tweets from parents this week sept,accidentally put grownup toothpaste on my todd...,2022,9,47,8,5.875

In [9]:
df.isnull().sum()

category                   0
authors                    0
date                       0
clean_headline             0
clean_description      19784
year                       0
month                      0
headline_char_count        0
headline_word_count        0
avg_word_length            0
dtype: int64

In [10]:
df['clean_description'] = df['clean_description'].fillna('No Description')

In [11]:
df.isnull().sum()

category               0
authors                0
date                   0
clean_headline         0
clean_description      0
year                   0
month                  0
headline_char_count    0
headline_word_count    0
avg_word_length        0
dtype: int64

In [12]:
from pandas.core.indexes import category
unique_category = df['category'].unique()
print(unique_category)
category_numbers = {}
i = 0
for emo in unique_category:
 category_numbers[emo] = i
 i += 1
print(category_numbers)

df['category'] = df['category'].map(category_numbers)

['category' 'U.S. NEWS' 'COMEDY' 'PARENTING' 'WORLD NEWS' 'CULTURE & ARTS'
 'TECH' 'SPORTS' 'ENTERTAINMENT' 'POLITICS' 'WEIRD NEWS' 'ENVIRONMENT'
 'EDUCATION' 'CRIME' 'SCIENCE' 'WELLNESS' 'BUSINESS' 'STYLE & BEAUTY'
 'FOOD & DRINK' 'MEDIA' 'QUEER VOICES' 'HOME & LIVING' 'WOMEN'
 'BLACK VOICES' 'TRAVEL' 'MONEY' 'RELIGION' 'LATINO VOICES' 'IMPACT'
 'WEDDINGS' 'COLLEGE' 'PARENTS' 'ARTS & CULTURE' 'STYLE' 'GREEN' 'TASTE'
 'HEALTHY LIVING' 'THE WORLDPOST' 'GOOD NEWS' 'WORLDPOST' 'FIFTY' 'ARTS'
 'DIVORCE']
{'category': 0, 'U.S. NEWS': 1, 'COMEDY': 2, 'PARENTING': 3, 'WORLD NEWS': 4, 'CULTURE & ARTS': 5, 'TECH': 6, 'SPORTS': 7, 'ENTERTAINMENT': 8, 'POLITICS': 9, 'WEIRD NEWS': 10, 'ENVIRONMENT': 11, 'EDUCATION': 12, 'CRIME': 13, 'SCIENCE': 14, 'WELLNESS': 15, 'BUSINESS': 16, 'STYLE & BEAUTY': 17, 'FOOD & DRINK': 18, 'MEDIA': 19, 'QUEER VOICES': 20, 'HOME & LIVING': 21, 'WOMEN': 22, 'BLACK VOICES': 23, 'TRAVEL': 24, 'MONEY': 25, 'RELIGION': 26, 'LATINO VOICES': 27, 'IMPACT': 28, 'WEDDINGS': 29, 'COLLEGE': 30, 'PARENTS': 31, 'ARTS & CULTURE': 32, 'STYLE': 33, 'GREEN': 34, 'TASTE': 35, 'HEALTHY LIVING': 36, 'THE WORLDPOST': 37, 'GOOD NEWS': 38, 'WORLDPOST': 39, 'FIFTY': 40, 'ARTS': 41, 'DIVORCE': 42}

In [13]:
df

,category,authors,date,clean_headline,clean_description,year,month,headline_char_count,headline_word_count,avg_word_length
0,0,authors,date,clean_headline,clean_description,year,month,headline_char_count,headline_word_count,avg_word_length
1,1,"Carla K. Johnson, AP",2022-09-23,over million americans roll up sleeves for omi...,health experts said it is too early to predict...,2022,9,73,10,7.3
2,1,Mary Papenfuss,2022-09-23,american airlines flyer charged banned for lif...,he was subdued by passengers and crew when he ...,2022,9,88,13,6.769230769230769
3,2,Elyse Wanshel,2022-09-23,of the funniest tweets about cats and dogs thi...,until you have a dog you dont understand what ...,2022,9,57,11,5.181818181818182
4,3,Caroline Bologna,2022-09-23,the funniest tweets from parents this week sept,accidentally put grownup toothpaste on my todd...,2022,9,47,8,5.875
...,...,...,...,...,...,...,...,...,...,...
206637,6,"Reuters, Reuters",2012-01-28,rim ceo thorsten heins significant plans for b...,verizon wireless and att are already promoting...,2012,1,55,8,6.875
206638,7,Unknown,2012-01-28,maria sharapova stunned by victoria azarenka i...,afterward azarenka more effusive with the pres...,2012,1,69,10,6.9
206639,7,Unknown,2012-01-28,giants over patriots jets over colts among mos...,leading up to super bowl xlvi the most talked ...,2012,1,95,16,5.9375
206640,7,Unknown,2012-01-28,aldon smith arrested ers linebacker busted for...,correction an earlier version of this story in...,2012,1,50,8,6.25
206641,7,Unknown,2012-01-28,dwight howard rips teammates after magic loss ...,the fivetime allstar center tore into his team...,2012,1,56,9,6.222222

In [14]:
df['clean_headline'] = df['clean_headline'].apply(lambda x : x.lower())

In [15]:
import string
def remove_punctuation(text):
    return text.translate(
        str.maketrans('', '', string.punctuation)
    )

df['clean_headline'] = df['clean_headline'].apply(remove_punctuation)
df['clean_description'] = df['clean_description'].apply(remove_punctuation)

In [16]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['clean_headline'] = df['clean_headline'].apply(remove_numbers)

In [17]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [18]:
stop_words = set(stopwords.words('english'))

df.loc[1]['clean_headline']

'over million americans roll up sleeves for omicrontargeted covid boosters'

In [19]:
def remove(txt):
  words = txt.split()
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)

  return ' '.join(cleaned)

df['clean_headline'] = df['clean_headline'].apply(remove)

df.loc[1]['clean_headline']

'million americans roll sleeves omicrontargeted covid boosters'

In [20]:
df.head()

,category,authors,date,clean_headline,clean_description,year,month,headline_char_count,headline_word_count,avg_word_length
0,0,authors,date,cleanheadline,cleandescription,year,month,headline_char_count,headline_word_count,avg_word_length
1,1,"Carla K. Johnson, AP",2022-09-23,million americans roll sleeves omicrontargeted...,health experts said it is too early to predict...,2022,9,73,10,7.3
2,1,Mary Papenfuss,2022-09-23,american airlines flyer charged banned life pu...,he was subdued by passengers and crew when he ...,2022,9,88,13,6.769230769230769
3,2,Elyse Wanshel,2022-09-23,funniest tweets cats dogs week sept,until you have a dog you dont understand what ...,2022,9,57,11,5.181818181818182
4,3,Caroline Bologna,2022-09-23,funniest tweets parents week sept,accidentally put grownup toothpaste on my todd...,2022,9,47,8,5.875

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X_train, X_test, y_train, y_test = train_test_split(df['clean_headline'], df['category'], test_size=0.20, random_state=42)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
tfidf = TfidfVectorizer(max_features=10000)

X = tfidf.fit_transform(df['clean_headline'])
y = df['category']

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
lr = LogisticRegression(max_iter=1000)

lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

lr_acc = accuracy_score(y_test, y_pred_lr)

print("Logistic Regression Accuracy =", lr_acc)

Logistic Regression Accuracy = 0.5621234484260447

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

X = df['clean_headline']
y = df['category']

tfidf = TfidfVectorizer(max_features=10000)

X = tfidf.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

rf_acc = accuracy_score(y_test, y_pred_rf)

print("Random Forest Accuracy =", rf_acc)

Random Forest Accuracy = 0.47697742505262647

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
X = df['clean_headline']
y = df['category']

tfidf = TfidfVectorizer(max_features=10000)

X = tfidf.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

nb = MultinomialNB()

nb.fit(X_train, y_train)

y_pred_nb = nb.predict(X_test)

nb_acc = accuracy_score(y_test, y_pred_nb)

print("Naive Bayes Accuracy =", nb_acc)

Naive Bayes Accuracy = 0.4905514287788236